# Generated by Django 6.0.2 on 2026-05-28 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='asaas_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
