# Generated by Django 6.0.2 on 2026-07-08 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_vehicleicon'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsCommandHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.IntegerField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('status_code', models.IntegerField(default=-1)),
                ('sms_market_id', models.CharField(blank=True, max_length=100, null=True)),
                ('direction', models.CharField(default='outbound', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
